### PR TITLE
Increase gas limit

### PR DESCRIPTION
**Pull request by chrismarino**
This is more of a feature request than a PR ready to merge. It would be great to be able to change the suggested gas limit for my validator. 

I've made some possible changes, but TBH, not sure what the proper way should be to config the gas limit. It interacts with MEV and not sure if/how the EC should be configured.

This PR does not change the CSM_VC, or the EC, which probably need to have similar changes.

Happy to make more updates to this if there is a preferred approach.

### CODE REVIEW

**Comment by chrismarino** [comment]
Also, I have not tested this beyond the config change. Not sure if 50M is the right value.

**Comment by coincashew** [comment]
Thanks for your PR!
Looks promising and is a great start. I will need to test it out.

Nimbus appears to require the config change on the Nimbus CL configuration, but your change on the Nimbus VC might work too.

36M is the right value as of Dec 2024, as can be checked on 
https://pumpthegas.org/

As for where the gas limit is modified, the docs suggest

Consensus Client ( for externally produced blocks with MEVboost)
and
Execution Client (for locally produced blocks)


```
SOLO STAKERS - What you can do
If you are a solo staker you can increase the gas limit today by adding a flag to your client configuration.

If you use Dappnode you can go to your client package > config > show advanced editor > EXTRA_OPTS

Consensus Client (externally produced blocks)
# Lighthouse (validator client)
--gas-limit 36000000

# Lodestar (validator client)
--defaultGasLimit 36000000

# Nimbus
--suggested-gas-limit=36000000

# Prysm (validator client)
--suggested-gas-limit 36000000

# Teku
--Xvalidators-builder-registration-default-gas-limit=36000000
Execution Client (locally produced blocks)
# Besu
--target-gas-limit 36000000

# Erigon
--miner.gaslimit 36000000

# Geth
--miner.gaslimit 36000000

# Nethermind
--Blocks.TargetBlockGasLimit 36000000

# Reth
--builder.gaslimit 36000000
```

**Comment by chrismarino** [comment]
Its a bit confusing as to what needs to get reconfigured. I think most people use MEV external block builders, so didn't think EthPillar needed to add the config option to the Execution Clients. For Consensus Clients, not sure if the Consensus or Validator, or both need to set the flag to the higher value. My PR was only for the validator. But having 2 things to change is a bit confusing.  But setting two client config from one menu item also seemed pretty confusing. Not even sure what happens if only one is set?  Potential foot-gun, for sure.

Maybe someone here has the definitive answer for how this should be set.

**Comment by chrismarino** [comment]
I think I'm going to close out this PR. After looking into this whole topic, I'm not sure this kind of config change deserves a spot in the system. I think it might be simpler/better to just let the client teams change their defaults when the gas limit is actually increased.  Anyone that wants to signal higher gas can change their config directly...

**Comment by coincashew** [comment]
Agreed, especially on the last point. Those motivated will change. Defaults in clients are coming or already here.

:+1:  for engaging and iterating on this PR.

**Pull request closed without merging**
