### PR TITLE
Added note about needing to load daemon.

### PR DESCRIPTION
**Pull request by chrismarino**
Had some problems with my node because I didn't reloading daemon after using the config option. Added a note.

### CODE REVIEW

**Comment by chrismarino** [comment]
Sorry about the giant diff in that last commit. I formatted my file and a lot of whitespace changed. Otherwise, just a few lines changed for text and an addition to the header...

**Comment by coincashew** [comment]
I am unclear what went wrong. 

A user should not need to know about manually reloading the daemon.  As a general rule, notes are discouraged, as most won't read even if it's spelled out infront of them. Less is more. 

It shoudl just work.

Did you change a configuration manually via the terminal and expect it to be live?

**Comment by chrismarino** [comment]
After initial install, I had to I change the config, but said 'No' when asked to restart. Then went back to restart using the other command, which does not reload the config. Seems obvious now, but in the moment I could not figure it out. Spent a lot of time trying to get it all to work. This was a migration from a stand-along CSM validatory, so not a happy path scenario.

**Comment by chrismarino** [comment]
The other changes are just cosmetic. Added some header info on use of CSM plugin, etc.

**Comment by coincashew** [comment]
Understood, so it seems like the best approach would be to always reload after editing, but leave the restart optional. That would have prevented your confusion and headscratching .

Will review tomorrow, cosmetic is always :+1:

**Comment by chrismarino** [comment]
Yes, that would work. The Title of the submenu is clear (i.e. 'Reload daemon and restart services'), but the message only says 'Do you want to restart validator'? Which is accurate, but without an understanding of the actual steps required to update a service config, how would you know how/when to reload the config. Reloading after editing would def fix.

**Comment by coincashew** [comment]
The pull request should be more specific, ideally two PRs, one for cosmetic and another for wording, rather than changing all those whitespaces. 

Rather than the wording change, I'd prefer a change in logic -- always reload on edit. Prompt to restart.

I can incorporate this in future changes or feel free to re-submit new PRs.

**Pull request closed without merging**
